### ISSUE TITLE
Attempt to get length of local 'v' (a nil value)

### ISSUE THREAD

**Issue by BX442** [pixelwhipped/ModMash#1]
Error while running event modmash::on_tick (ID 0)
__modmash__/control.lua:155: attempt to get length of local 'v' (a nil value)
stack traceback:
	__modmash__/control.lua:155: in function <__modmash__/control.lua:125>

You need to add an extra check:
```
	for k=1, #modmash.ticks do local v = modmash.ticks[k]	
		v()
		local alerts = game.players[1].get_alerts{}
		if #alerts>0 then
			for k=1, #alerts do
				local v = alerts[k] 
				if alerts[k] ~= nil then  --<==========
					for j=1, #v do local w = v[j] 
						for l=1, #w do
							local x = w[l] 
							if  x~= nil and x.target~=nil then
								if (x.target.name ~= nil and starts_with(x.target.name,"biter")) or x.target.prototype.subgroup.name=="enemies" then
									game.players[1].remove_alert{entity = x.target}
								end
							end
						end
					end
				end
			end
		end
	end
```

**Comment by BX442** [comment]
This error occurs if you play Factorio for some time and then try to place a drawing with more than five items in the building(factory) from the Factorissimo2 mod.
The first 8 hours of the game did not cause any errors.

**Comment by pixelwhipped** [comment]
Checking now.  I’ll post an update soon with the check and do a test with factorissimo2 later on.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
