### ISSUE TITLE
Path "false" not matching the resource path

### ISSUE THREAD

**Issue by BX442** [pixelwhipped/ModMash#2]
Path false not matching the resource path pattern: __source__/path: false

When loading ModMash mod together with "Angel's Refining" mod the error described above appears.

Code causing an error:
line: 1006 "icon = false,"

If this line to change for 'icon = "__modmash__/graphics/icons/alien-conversion-uranium.png",' it is still operating normally

**Comment by pixelwhipped** [comment]
it was pointing to contain_icon not icons, so icons was of course nil making icon = false invalid
